# Generated by Django 5.2.6 on 2025-09-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.JSONField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('emotions', models.JSONField(default=list)),
                ('topics', models.JSONField(default=list)),
            ],
        ),
    ]
